params:
  algo:
    name: a2c_continuous
  config:
    bounds_loss_coef: 0.0001
    clip_value: true
    critic_coef: 4
    e_clip: 0.2
    entropy_coef: 0.0
    env_name: rlgpu
    full_experiment_name: ${.name}
    gamma: 0.99
    grad_norm: 1.0
    horizon_length: 16
    kl_threshold: 0.008
    learning_rate: 3e-4
    lr_schedule: adaptive
    max_epochs: ${resolve_default:250,${....max_iterations}}
    mini_epochs: 8
    minibatch_size: 8192
    mixed_precision: false
    multi_gpu: ${....multi_gpu}
    name: ${resolve_default:BallBalanceGPT,${....experiment}}
    normalize_advantage: true
    normalize_input: true
    normalize_value: true
    num_actors: ${....task.env.numEnvs}
    ppo: true
    reward_shaper:
      scale_value: 0.1
    save_best_after: 50
    save_frequency: 100
    score_to_win: 20000
    seq_len: 4
    tau: 0.95
    truncate_grads: true
  load_checkpoint: ${if:${...checkpoint},True,False}
  load_path: ${...checkpoint}
  model:
    name: continuous_a2c_logstd
  network:
    mlp:
      activation: elu
      initializer:
        name: default
      regularizer:
        name: None
      units:
      - 128
      - 64
      - 32
    name: actor_critic
    separate: false
    space:
      continuous:
        fixed_sigma: true
        mu_activation: None
        mu_init:
          name: default
        sigma_activation: None
        sigma_init:
          name: const_initializer
          val: 0
  seed: ${...seed}
