asymmetric_obs: true
params:
  algo:
    name: a2c_continuous
  config:
    bounds_loss_coef: 0.0001
    central_value_config:
      clip_value: true
      kl_threshold: 0.016
      learning_rate: 0.0005
      lr_schedule: linear
      mini_epochs: ${..mini_epochs}
      minibatch_size: ${..num_actors}
      network:
        central_value: true
        mlp:
          activation: elu
          d2rl: false
          initializer:
            name: default
          regularizer:
            name: None
          units:
          - 512
          - 512
          - 256
          - 128
        name: actor_critic
      normalize_input: true
      schedule_type: standard
      truncate_grads: true
    clip_value: true
    critic_coef: 4
    e_clip: 0.2
    entropy_coef: 0.0
    env_name: rlgpu
    full_experiment_name: ${.name}
    gamma: 0.99
    grad_norm: 1.0
    horizon_length: 8
    kl_threshold: 0.016
    learning_rate: 0.0003
    lr_schedule: constant
    max_epochs: ${resolve_default:20000,${....max_iterations}}
    mini_epochs: 4
    minibatch_size: ${.num_actors}
    mixed_precision: false
    multi_gpu: ${....multi_gpu}
    name: ${resolve_default:TrifingerGPT,${....experiment}}
    normalize_advantage: true
    normalize_input: true
    normalize_value: true
    num_actors: ${....task.env.numEnvs}
    player:
      deterministic: true
      games_num: 20000
      print_stats: false
    ppo: true
    print_stats: true
    reward_shaper:
      scale_value: 0.01
    save_best_after: 100
    save_frequency: 100
    schedule_type: standard
    score_to_win: 500000
    seq_len: 4
    tau: 0.95
    truncate_grads: true
    use_experimental_cv: true
  load_checkpoint: ${if:${...checkpoint},True,False}
  load_path: ${...checkpoint}
  model:
    name: continuous_a2c_logstd
  network:
    mlp:
      activation: elu
      d2rl: false
      initializer:
        name: default
      regularizer:
        name: None
      units:
      - 256
      - 256
      - 128
      - 128
    name: actor_critic
    separate: false
    space:
      continuous:
        fixed_sigma: true
        mu_activation: None
        mu_init:
          name: default
        sigma_activation: None
        sigma_init:
          name: const_initializer
          val: 0
  seed: ${...seed}
